export const listData = [
  {
    id: 1,
    title: "A Great Apartment Next to the Beach!",
    img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 2,
    bathroom: 1,
    price: '201000',
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
    status:"For Sale",
    type:"apartment",
     many:"sale",
     slug:"p-1",
    school: "200m away",
    bus: "100m away",
    restaurant: "30m away",
    description:"Nestled in the heart of the city, this sleek modern apartment offers a luxurious urban living experience. Boasting two spacious bedrooms and two pristine bathrooms, the open-concept living area seamlessly integrates with a fully-equipped kitchen, perfect for entertaining. Residents enjoy exclusive access to a rooftop terrace with stunning city views, a state-of-the-art gym, and round-the-clock security. Available for sale at $201000, this apartment is ideal for those seeking convenience and style.",
    img1:"https://i.pinimg.com/originals/26/58/06/265806abb62c82c7cfdaeb097d5245d2.jpg",
    img2:"https://i.ytimg.com/vi/-6EylAMOK9U/maxresdefault.jpg"
    
  },
  {
    id: 2,
    title: "An Awesome Apartment Near the Park! Almost too good to be true!",
    img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 3,
    bathroom: 2,
    price: '1500',
    address: "789 Oxford Street, London",
    latitude: 52.4862,
    longitude: -1.8904,
    status:"for rent",
    type:"cottage",
     many:"rent",
     slug:"p-2",
    school: "280m away",
  bus: "160m away",
  restaurant: "100m away",
  description:"Located in a tranquil suburb, this charming cottage provides a cozy retreat from the hustle and bustle of city life. The home features three comfortable bedrooms, one and a half bathrooms, and a spacious backyard perfect for family gatherings. A modern kitchen with contemporary appliances complements the inviting living spaces. With parks, schools, and local shops just a stone's throw away,  Available for rent at $2,500 per month,offering a perfect blend of comfort and convenience.",
  img1:"https://i.pinimg.com/originals/9b/2a/41/9b2a41a75eef0ad4051a841f2d45b525.jpg",
  img2:"https://www.build-review.com/wp-content/uploads/2021/01/large-house.jpg"
  },
  {
    id: 3,
    title: "A New Apartment in the City!",
    img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 1,
    bathroom: 1,
    price: '6800',
    address: "101 Baker Street, London",
    latitude: 53.4808,
    longitude: -2.2426,
    status:"for rent",
    type:"apartment",
     many:"rent",
     slug:"p-3",  
      school: "350m away",
  bus: "150m away",
  restaurant: "80m away",
  description:"Embrace a tranquil countryside lifestyle with this charming farmhouse. The property includes three bedrooms, two bathrooms, a barn, and a large garden ideal for sustainable living. Enjoy the serenity of nearby vineyards and rolling hills while staying close to essential amenities. This farmhouse offers a unique blend of rustic charm and modern comforts, priced at $6800 per Month",
  img1:"https://i.pinimg.com/originals/18/9a/87/189a8770016da26197dc81b3e515d601.png",
  img2:"https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2019/3/27/0/HUHH2019-Waterfront_Osterville-MA_005.jpg.rend.hgtvcom.616.411.suffix/1553706598088.jpeg"
  },
  {
    id: 4,
    title: "Great Location! Great Price! Great Apartment!",
    img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 2,
    bathroom: 1,
    price: '800000',
    address: "234 Kingsway, London,",
    latitude: 53.8008,
    longitude: -1.5491,
    status:"for sale",
    type:"apartment",
     many:"sale",
    slug:"p-4",
      school: "290m away",
  bus: "50m away",
  restaurant: "50m away",
  description:"Escape to a secluded mountain retreat with this rustic cabin, surrounded by breathtaking natural beauty. Featuring four bedrooms, three bathrooms, and a large deck, this home is designed for relaxation and adventure. A wood-burning fireplace adds a cozy touch to the spacious living areas. Nearby hiking trails and skiing opportunities make this cabin a perfect getaway, listed for sale at $800,000.",
  img1:"https://i.pinimg.com/736x/da/79/fc/da79fc167b8b23c82d20f561c3ca0a4f.jpg",
  img2:"https://thumbs.dreamstime.com/b/modern-house-interior-5388318.jpg"
  },
  {
    id: 5,
    title: "Exclusive Beachfront Villa",
    img: "https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 3,
    bathroom: 2,
    price: '450000',
    address: "567 Victoria Road, London",
    latitude: 53.4084,
    longitude: -2.9916,
    status:"for sale",
    type:"Villa",
     many:"sale",
     slug:"p-5",
       school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:"Embrace a tranquil countryside lifestyle with this charming farmhouse. The property includes three bedrooms, two bathrooms, a barn, and a large garden ideal for sustainable living. Enjoy the serenity of nearby vineyards and rolling hills while staying close to essential amenities. This farmhouse offers a unique blend of rustic charm and modern comforts, priced at $450,000.",
  img1:"https://static.vecteezy.com/system/resources/thumbnails/023/307/478/small_2x/ai-generative-exterior-of-modern-luxury-house-with-garden-and-beautiful-sky-photo.jpg",  img2:"https://thumbs.dreamstime.com/b/house-interior-29639345.jpg"
  },

  {
    id: 6,
    title: "Sleek Downtown Suite",
    img: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 1,
    bathroom: 1,
    price: '2800',
    address: "890 Regent Street, London",
    latitude: 54.9783,
    longitude: -1.6174,
    status:"for rent",
    type:'apartment',
    many:"rent",
    slug:"p-6",
      school: "450m away",
  bus: "90m away",
  restaurant: "100m away",
  description:"Located in a green community, this eco-friendly smart home combines sustainability with modern technology. It includes three bedrooms, two bathrooms, solar panels, and energy-efficient appliances. Smart home technology enhances convenience and reduces the environmental footprint. Community gardens and other eco-friendly amenities make this home a perfect choice for environmentally conscious buyers, priced at $7000 per month",
  img1:"https://us.123rf.com/450wm/visoot/visoot2307/visoot230701142/208218826-residential-architecture-exterior-design-house-modern-minimalist-private-houses.jpg",
  img2:"https://cdn.homedit.com/wp-content/uploads/2022/01/Inside-bel-air-mansion-living-room.jpg"
  },
  {
    id: 7,
    title: "Serene Coastal Villa",
    img: "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 2,
    bathroom: 1,
    price: '550000',
    address: "112 Piccadilly, London",
    latitude: 53.3811,
    longitude: -1.4701,
    status:"for sale",
    type:"Villa",
    many:"sale",
    slug:"p-7",
      school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:"Located in a family-friendly neighborhood, this spacious home is designed for comfortable family living. It offers five bedrooms, three bathrooms, a large backyard for kids to play, and a three-car garage. Excellent schools, parks, and community centers are all nearby, making it an ideal place to raise a family. This home is listed for sale at $550,000.",
  img1:"https://static.vecteezy.com/system/resources/thumbnails/023/331/645/small_2x/ai-generative-exterior-of-modern-luxury-house-with-garden-and-beautiful-sky-photo.jpg",
  img2:"https://cdn.homedit.com/wp-content/uploads/2022/01/Mansion-living-room-decor-1024x653.jpg"
  },
  {
    id: 8,
    title: "Opulent Seaside Retreat",
    img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    bedroom: 5,
    bathroom: 5,
    price: '955500',
    address: "8765 Main High Street, London",
    latitude: 51.4545,
    longitude: -2.5879,
    status:"for Sale",
    type:"Villa",
    many:"sale",
    slug:"p-8",
    description:"Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    img1:"https://static.vecteezy.com/system/resources/thumbnails/023/309/774/small/ai-generative-exterior-of-modern-luxury-house-with-garden-and-beautiful-sky-photo.jpg",
    img2:"https://loveincorporated.blob.core.windows.net/contentimages/gallery/750d821d-6bab-4d29-a689-e4c92df8f21f-mansions-with-massive-secrets-modern-mansion-inside.jpg",
    school: "250m away",
  bus: "190m away",
  restaurant: "50m away",
    
  },

  {
    id:9,
    title:"Modern Townhouse Retreat",
    img:"https://i2.au.reastatic.net/800x600/666aa9f84688b8cd3d67840e5c3c654ff2e49732b63a82ebf107ac7728e51ce0/image.jpg",
    img1:"https://cdn.homedsgn.com/wp-content/uploads/2013/10/Stunning-Modern-Townhouse-Living-02.jpg",
    img2:"https://cdn.homedsgn.com/wp-content/uploads/2013/10/Stunning-Modern-Townhouse-Living-01.jpg",
    bathroom:2,
    bedroom:3,
    price:"760000",
    address:" New York, NY 11201 United States",
    latitude:51.3453,
    longitude:-2.5454,
    status:"for Sale",
    type:"townhouse",
    many:"sale",
    slug:"p-9",
    description:"Discover the perfect blend of contemporary design and comfortable living in this Modern Townhouse Retreat. Nestled in a vibrant urban neighborhood, this stunning townhouse offers a spacious and open floor plan, ideal for both relaxation and entertainment. The sleek, modern kitchen is equipped with top-of-the-line stainless steel appliances, quartz countertops, and ample storage space. Large windows throughout the home provide an abundance of natural light, creating a bright and airy atmosphere. The master suite is a true oasis, featuring a luxurious en-suite bathroom with a walk-in shower and a spacious walk-in closet. Additional bedrooms are generously sized and perfect for family, guests, or a home office. The private rooftop terrace offers panoramic city views and is perfect for hosting gatherings or enjoying a quiet evening under the stars. Conveniently located near trendy shops, fine dining, and excellent schools, this Modern Townhouse Retreat is the epitome of urban living. Enjoy the best of both worlds with easy access to the bustling city life and the tranquility of a private home. This townhouse is a rare find and a true gem for those seeking a stylish and modern living space.",
    school: "258m away",
  bus: "90m away",
  restaurant: "150m away",
  },

  {
    id:10,
    title:"Charming Suburban Townhouse",
    img:"https://www.gjgardner.com.au/wp-content/uploads/2023/11/big-70.jpg",
    img1:"https://cdn.decoist.com/wp-content/uploads/2013/11/Artful-living-room-in-a-modern-townhome.jpg",
    img2:"https://www.katicurtisdesign.com/wp-content/uploads/2021/01/modern-townhouse-interior-designer-kati-curtis-design-4.jpg",
    bathroom:3,
    bedroom:3,
    price:"7600",
    address:" Brooklyn, New York, NY 11201",
    latitude:51.3453,
    longitude:-2.5454,
    status:"for Rent",
    type:"townhouse",
    many:"rent",
    slug:"p-10",
    description:"Discover the perfect blend of contemporary design and comfortable living in this Modern Townhouse Retreat. Nestled in a vibrant urban neighborhood, this stunning townhouse offers a spacious and open floor plan, ideal for both relaxation and entertainment. The sleek, modern kitchen is equipped with top-of-the-line stainless steel appliances, quartz countertops, and ample storage space. Large windows throughout the home provide an abundance of natural light, creating a bright and airy atmosphere. The master suite is a true oasis, featuring a luxurious en-suite bathroom with a walk-in shower and a spacious walk-in closet. Additional bedrooms are generously sized and perfect for family, guests, or a home office. The private rooftop terrace offers panoramic city views and is perfect for hosting gatherings or enjoying a quiet evening under the stars. Conveniently located near trendy shops, fine dining, and excellent schools, this Modern Townhouse Retreat is the epitome of urban living. Enjoy the best of both worlds with easy access to the bustling city life and the tranquility of a private home. This townhouse is a rare find and a true gem for those seeking a stylish and modern living space..",
    school: "258m away",
  bus: "98m away",
  restaurant: "160m away",
  },


  {
    id:11,
    title:"Picturesque Coastal Cottage",
    img:"https://cdn11.bigcommerce.com/s-g95xg0y1db/images/stencil/1280x1280/b/cottage%20house%20plan%20-%20cherokee__17187.original.jpg",
    img1:"https://havenly.com/blog/wp-content/uploads/2021/11/V01-1710x970.jpeg",
    img2:"https://img.freepik.com/premium-photo/modern-cottage-sitting-room-decor-interior-design-living-room-furniture-neutral-colours-fireplace-home-decor-elegant-english-country-house-style-postprocessed-generative-ai_360074-77598.jpg",
    bathroom:3,
    bedroom:3,
    price:"407,600",
    address:" Cape Cod, Massachusetts, MA 0263 United States",
    latitude:51.3453,
    longitude:-2.5454,
    status:"for Sale",
    type:"cottage",
    many:"sale",
    slug:"p-11",
    description:"Welcome to this Picturesque Coastal Cottage, a quintessential seaside retreat nestled along the tranquil shores of Cape Cod. This charming cottage offers the perfect blend of classic New England charm and modern amenities, creating an idyllic escape for those who dream of coastal living. Upon entering, you are greeted by a warm and inviting living space, featuring rustic wooden beams and a stone fireplace that adds to the cozy ambiance. Large windows flood the space with natural light and offer stunning views of the ocean. The open-concept kitchen, equipped with updated appliances and granite countertops, includes a delightful breakfast nook where you can enjoy your morning coffee while gazing at the sea. The master bedroom serves as a private haven, complete with its own balcony that provides a panoramic view of the ocean—perfect for relaxing after a long day. Additional bedrooms are spacious and well-designed, offering comfort and privacy for family and guests alike. Step outside to the expansive deck and beautifully landscaped yard, ideal for outdoor entertaining and soaking up the sun. The proximity to the beach is unparalleled, with just a few steps separating you from the sandy shores and the soothing sound of waves. Priced at $1,250,000, this cottage not only offers a serene and picturesque lifestyle but also an excellent investment in a prime coastal location. Situated in a quiet and friendly neighborhood, it is also conveniently close to local shops, fine dining, and a variety of recreational activities. This Picturesque Coastal Cottage is more than just a home—it's a lifestyle. Don’t miss your opportunity to own a slice of Cape Cod’s enchanting coastal beauty, where every day feels like a holiday. Come and experience the timeless charm and modern comforts of this extraordinary property.",
    school: "258m away",
  bus: "98m away",
  restaurant: "160m away",
  },


  {
    id:12,
    title:"Stunning Skyline Penthouse",
    img:"https://www.milldistricthealdsburg.com/app/uploads/2023/02/15-canopy-penthouse-401-primary-bedroom-patio-2400x1350-1.jpg",
    img1:"https://www.milldistricthealdsburg.com/app/uploads/2023/02/11-canopy-penthouse-401-primary-bedroom-patio-2400x1350-1.jpg",
    img2:"https://media.v2.siweb.es/uploaded_thumb_big/9fb7c789c323c64d5c4e4fcb00491d67/post_1_abril_penthouses.jpg",
    bathroom:3,
    bedroom:2,
    price:"3,500,000",
    address:"9876 Skyview Avenue New York, NY 10001",
    latitude:51.3453,
    longitude:-2.5454,
    status:"for Sale",
    type:"penthouse",
    many:"sale",
    slug:"p-12",
    description:"Discover the epitome of luxury living in this Stunning Skyline Penthouse, perched high above the vibrant streets of New York City. This exquisite penthouse offers an unparalleled living experience, combining sophisticated design with breathtaking views of the iconic city skyline. As you step inside, you are greeted by an expansive open-plan living area, featuring floor-to-ceiling windows that flood the space with natural light and provide panoramic views of the cityscape. The modern, state-of-the-art kitchen is a chef’s dream, equipped with top-of-the-line appliances, sleek cabinetry, and an oversized island perfect for entertaining. The master suite is a private oasis, boasting a spacious layout, a walk-in closet, and a luxurious en-suite bathroom with a soaking tub and rain shower. Wake up to stunning sunrises and unwind with spectacular sunsets from the comfort of your own bedroom. Additional bedrooms are equally impressive, offering ample space and stunning views, ensuring comfort for family and guests. Step outside to the private terrace, an ideal spot for alfresco dining, entertaining, or simply enjoying the sweeping views of the city. The penthouse also includes exclusive amenities such as a fitness center, rooftop pool, and 24-hour concierge service, ensuring a lifestyle of convenience and luxury.Priced at $3,500,000, this penthouse not only offers a premium living experience but also a prime location in the heart of New York City. Situated within walking distance to world-class dining, shopping, and entertainment, it provides easy access to everything the city has to offer. This Stunning Skyline Penthouse is more than just a residence; it's a statement of elegance and prestige. Don’t miss the opportunity to own this extraordinary property, where modern luxury meets the timeless beauty of the New York skyline. Experience the height of sophistication and comfort in your new home.",
    school: "258m away",
  bus: "198m away",
  restaurant: "170m away",
  },




];

export const singlePostData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 1200,
  images: [
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: 51.5074,
  longitude: -0.1278,
  city: "London",
  address: "1234 Broadway St",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
};

export const userData = {
  id: 1,
  name: "John Doe",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};